"""empty message

Revision ID: 0408d357d7dc
Revises: 5c4545a337c0
Create Date: 2019-08-30 14:35:10.119691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0408d357d7dc'
down_revision = '5c4545a337c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fermentable', 'custom',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('hop', sa.Column('custom', sa.Boolean(), nullable=True))
    op.add_column('yeast', sa.Column('custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeast', 'custom')
    op.drop_column('hop', 'custom')
    op.alter_column('fermentable', 'custom',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
