"""empty message

Revision ID: 12a58ed658a9
Revises: 3eec33146008
Create Date: 2019-09-11 14:21:24.596101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a58ed658a9'
down_revision = '3eec33146008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_confirmation_id'), 'confirmation', ['id'])
    op.create_unique_constraint(op.f('uq_fermentable_id'), 'fermentable', ['id'])
    op.create_unique_constraint(op.f('uq_grain_id'), 'grain', ['id'])
    op.create_unique_constraint(op.f('uq_hop_id'), 'hop', ['id'])
    op.create_unique_constraint(op.f('uq_resettoken_id'), 'resettoken', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    op.create_unique_constraint(op.f('uq_yeast_id'), 'yeast', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_yeast_id'), 'yeast', type_='unique')
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_resettoken_id'), 'resettoken', type_='unique')
    op.drop_constraint(op.f('uq_hop_id'), 'hop', type_='unique')
    op.drop_constraint(op.f('uq_grain_id'), 'grain', type_='unique')
    op.drop_constraint(op.f('uq_fermentable_id'), 'fermentable', type_='unique')
    op.drop_constraint(op.f('uq_confirmation_id'), 'confirmation', type_='unique')
    # ### end Alembic commands ###
