"""empty message

Revision ID: 341e68276fff
Revises: ae006e3ebb6f
Create Date: 2019-08-18 16:37:36.177700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341e68276fff'
down_revision = 'ae006e3ebb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('hex_color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'hex_color')
    # ### end Alembic commands ###
