"""empty message

Revision ID: 373b9f4bf046
Revises: f031900bdbb2
Create Date: 2019-08-28 13:11:59.231286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373b9f4bf046'
down_revision = 'f031900bdbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_resettoken_id'), 'resettoken', ['id'])
    op.add_column('user', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    op.drop_constraint(op.f('uq_resettoken_id'), 'resettoken', type_='unique')
    # ### end Alembic commands ###
