"""empty message

Revision ID: 387f57055fc0
Revises: 4435edf1e75a
Create Date: 2019-08-15 13:12:02.848349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387f57055fc0'
down_revision = '4435edf1e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentable', sa.Column('category', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentable', 'category')
    # ### end Alembic commands ###
