"""empty message

Revision ID: 4435edf1e75a
Revises: e285b11cfacc
Create Date: 2019-08-15 13:04:20.556224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4435edf1e75a'
down_revision = 'e285b11cfacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentable', sa.Column('lovibond', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentable', 'lovibond')
    # ### end Alembic commands ###
