"""empty message

Revision ID: 57e8de8f6716
Revises: 387f57055fc0
Create Date: 2019-08-16 09:48:47.736439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8de8f6716'
down_revision = '387f57055fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeast', sa.Column('avg_attenuation', sa.Integer(), nullable=True))
    op.drop_column('yeast', 'min_attenuation_temp')
    op.drop_column('yeast', 'max_attenuation_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeast', sa.Column('max_attenuation_temp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yeast', sa.Column('min_attenuation_temp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('yeast', 'avg_attenuation')
    # ### end Alembic commands ###
