"""empty message

Revision ID: 60b567c1cb8c
Revises: 15e1b9c84e58
Create Date: 2019-08-23 12:58:51.028499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60b567c1cb8c'
down_revision = '15e1b9c84e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fermentable', 'category',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('fermentable', 'custom',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fermentable', 'lovibond',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fermentable', 'ppg',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fermentable', 'ppg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fermentable', 'lovibond',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fermentable', 'custom',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fermentable', 'category',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
