"""empty message

Revision ID: 6d077f8a6a73
Revises: 5b697389f71e
Create Date: 2019-06-28 13:38:02.160989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d077f8a6a73'
down_revision = '5b697389f71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_grains',
    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('grain_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grain_id'], ['grain.id'], name=op.f('fk_recipes_grains_grain_id_grain')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipes_grains_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'grain_id', name=op.f('pk_recipes_grains'))
    )
    op.create_table('recipes_yeasts',
    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('yeast_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pitch_temp', sa.Integer(), nullable=True),
    sa.Column('pitch_time', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipes_yeasts_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['yeast_id'], ['yeast.id'], name=op.f('fk_recipes_yeasts_yeast_id_yeast')),
    sa.PrimaryKeyConstraint('recipe_id', 'yeast_id', name=op.f('pk_recipes_yeasts'))
    )
    op.create_unique_constraint(op.f('uq_confirmation_id'), 'confirmation', ['id'])
    op.create_unique_constraint(op.f('uq_fermentable_id'), 'fermentable', ['id'])
    op.create_unique_constraint(op.f('uq_grain_id'), 'grain', ['id'])
    op.create_unique_constraint(op.f('uq_hop_id'), 'hop', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    op.create_unique_constraint(op.f('uq_yeast_id'), 'yeast', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_yeast_id'), 'yeast', type_='unique')
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_hop_id'), 'hop', type_='unique')
    op.drop_constraint(op.f('uq_grain_id'), 'grain', type_='unique')
    op.drop_constraint(op.f('uq_fermentable_id'), 'fermentable', type_='unique')
    op.drop_constraint(op.f('uq_confirmation_id'), 'confirmation', type_='unique')
    op.drop_table('recipes_yeasts')
    op.drop_table('recipes_grains')
    # ### end Alembic commands ###
