"""empty message

Revision ID: 716c32eda7f5
Revises: 
Create Date: 2019-07-27 21:37:47.023289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716c32eda7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('style', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'style')
    # ### end Alembic commands ###
