"""empty message

Revision ID: 84aa1baf3b1f
Revises: b9211f8555c2
Create Date: 2019-08-09 10:29:25.227769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84aa1baf3b1f'
down_revision = 'b9211f8555c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('icon', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'icon')
    # ### end Alembic commands ###
