"""empty message

Revision ID: 8b3f3e8a500f
Revises: b496e77efe81
Create Date: 2019-08-23 11:23:32.889946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3f3e8a500f'
down_revision = 'b496e77efe81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('private_recipe', sa.Boolean(), nullable=True))
    op.drop_column('recipe', 'private')
    op.add_column('recipes_yeasts', sa.Column('attenuation', sa.Integer(), nullable=True))
    op.drop_column('recipes_yeasts', 'attenutation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes_yeasts', sa.Column('attenutation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('recipes_yeasts', 'attenuation')
    op.add_column('recipe', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('recipe', 'private_recipe')
    # ### end Alembic commands ###
