"""empty message

Revision ID: 8dc668934b22
Revises: 8b3f3e8a500f
Create Date: 2019-08-23 12:40:27.451967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc668934b22'
down_revision = '8b3f3e8a500f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentable', sa.Column('custom', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('fermentable', 'custom')
    # ### end Alembic commands ###
