"""empty message

Revision ID: a5a3493ec573
Revises: 422af52a398b
Create Date: 2019-09-06 09:26:31.590249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5a3493ec573'
down_revision = '422af52a398b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_mash',
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=240), nullable=True),
    sa.Column('mash_type', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipes_mash_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('step', name=op.f('pk_recipes_mash'))
    )
    op.create_unique_constraint(op.f('uq_confirmation_id'), 'confirmation', ['id'])
    op.create_unique_constraint(op.f('uq_fermentable_id'), 'fermentable', ['id'])
    op.create_unique_constraint(op.f('uq_grain_id'), 'grain', ['id'])
    op.create_unique_constraint(op.f('uq_hop_id'), 'hop', ['id'])
    op.add_column('recipe', sa.Column('priming_level', sa.Float(), nullable=False))
    op.create_unique_constraint(op.f('uq_resettoken_id'), 'resettoken', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    op.create_unique_constraint(op.f('uq_yeast_id'), 'yeast', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_yeast_id'), 'yeast', type_='unique')
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_resettoken_id'), 'resettoken', type_='unique')
    op.drop_column('recipe', 'priming_level')
    op.drop_constraint(op.f('uq_hop_id'), 'hop', type_='unique')
    op.drop_constraint(op.f('uq_grain_id'), 'grain', type_='unique')
    op.drop_constraint(op.f('uq_fermentable_id'), 'fermentable', type_='unique')
    op.drop_constraint(op.f('uq_confirmation_id'), 'confirmation', type_='unique')
    op.drop_table('recipes_mash')
    # ### end Alembic commands ###
