"""empty message

Revision ID: ae006e3ebb6f
Revises: 57e8de8f6716
Create Date: 2019-08-16 16:04:56.626182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae006e3ebb6f'
down_revision = '57e8de8f6716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes_yeasts', sa.Column('attenutation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes_yeasts', 'attenutation')
    # ### end Alembic commands ###
