"""empty message

Revision ID: b496e77efe81
Revises: 505cabaa2fea
Create Date: 2019-08-23 11:21:08.898377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b496e77efe81'
down_revision = '505cabaa2fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('private_recipe', sa.Boolean(), nullable=False))
    op.drop_column('recipe', 'private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('recipe', 'private_recipe')
    # ### end Alembic commands ###
