"""empty message

Revision ID: b9211f8555c2
Revises: dafde6ac1cc7
Create Date: 2019-07-30 13:51:04.940665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9211f8555c2'
down_revision = 'dafde6ac1cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('batch_size', sa.Float(precision=1), nullable=True))
    op.add_column('recipe', sa.Column('boil_time', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('efficiency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'efficiency')
    op.drop_column('recipe', 'boil_time')
    op.drop_column('recipe', 'batch_size')
    # ### end Alembic commands ###
