"""empty message

Revision ID: dafde6ac1cc7
Revises: 716c32eda7f5
Create Date: 2019-07-27 21:47:56.059154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafde6ac1cc7'
down_revision = '716c32eda7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'created_date')
    # ### end Alembic commands ###
