"""empty message

Revision ID: e285b11cfacc
Revises: 
Create Date: 2019-08-15 11:21:12.232063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e285b11cfacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentable', sa.Column('ppg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentable', 'ppg')
    # ### end Alembic commands ###
