"""empty message

Revision ID: f031900bdbb2
Revises: b87ca0d820b3
Create Date: 2019-08-26 11:52:23.353774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f031900bdbb2'
down_revision = 'b87ca0d820b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resettoken',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_resettoken_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resettoken')),
    sa.UniqueConstraint('id', name=op.f('uq_resettoken_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resettoken')
    # ### end Alembic commands ###
